baseurl = "/"
languageCode = "en-us"
title = "Website of the MEE seminar"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/home/"
    weight = 1
[[menu.main]]
    name = "Speakers"
    url = "/speakers/"
    weight = 3
[[menu.main]]
    name = "Program"
    url = "/program/"
    weight = 2
[[menu.main]]
    name = "Registration"
    url = "/registration/"
    weight = 5
[[menu.main]]
    name = "Organizers"
    url = "/organizers/"
    weight = 4
[[menu.main]]
    name = "Editions"
    url = "/post"
    weight = 6
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7
    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "Image_MEE.png"

    [params.logo]
    url = "Image_MEE.png"
    width = 50
    height = 50
    alt = "Logo"
    
    [[redirects]]
    from = "https://meeseminar.netlify.app/"
    to = "https://meeseminar.netlify.app/home/"
    status = 301 

