---
title: Edition 2012
author: ~
date: '2012-05-22'
slug: edition-2012
categories: []
tags: []
---

# Programme 2012

## MARDI 22 MAI

9h - Acceuil, petit-déjeuné

9h20 - Présentation du séminaire

9h30-10h30 - Sandrine Maurice - Game theory and systems of reproduction

10h30-10h50 - Mickael Teixeira - How predators forage can promote positive indirect interactions between prey species

Pause

11h10-12h10 - Tom Van Dooren - Evolutionary modelling of life histories with a germ bank

12h10-12h30 - Jeanne Tonnabel - Optimal resource allocation in a serotinous plant species under different fire regimes

Déjeuner

14h-15h Nicolas Galtier - Markov models for molecular evolutionary processes

15h-15h20 Christelle Fraïsse - The hitchhiking effect of adaptive introgression in a hybrid zone

15h20-15h40 Claudio Quilodran - Titre à venir

Pause

16h-17h Luis Miguel Chevin - Genetic constraints on adaptation to a changing environment

17h-17h20 Olivier Cotto - Sénescence et migration

## MERCREDI 23 MAI

9h - Acceuil, petit-déjeuné

9h30-10h30 - Christophe Lett - Why and how can we study the connectivity of marine populations ?

10h30-10h50 - Laroche Fabien - Selection leads to dispersal niches in networks of quasi-neutral communities

Pause

11h20-11h50 Isabelle Gounan - The paradox of enrichment in metaecosystems

11h50-12h10 Fanny Gascuel - Disentangling the roles of host resistance and population structure on the persistence of a highly virulent disease : the Malagasy plague

Déjeuner

13h30-14h30 Jean-Baptiste André - Biological markets and the evolution of human coopération

14h30-14h50 Loic Etienne - To be choosy or not ? The evolution of choosiness in a complex world

14h50-15h10 Julien Barthes - Évolution d’un facteur génétique sexuellement antagoniste en population socialement stratifiée chez l’Homme

Pause

15h30-16h30 Bernard Godelle - Que reste-t-il d’un modèle, 10 ans après ?

# Organisateurs 2012

**Olivier Cotto** - doctorant (2ème année) à l’Institut des Sciences de l’Evolution (Montpellier) sous la direction d’Ophélie Ronce. Je travaille sur l’évolution du vieillissement en paysages hétérogènes.

**Jeanne Tonnabel** - doctorant (2ème année) à l’Institut des Sciences de l’Evolution (Montpellier) sous la direction d’Isabelle Olivieri. Je m’intéresse à l’évolution des traits d’histoire de vie chez les plantes pérennes dans les environnements soumis au feu.

**François Blanquart** - doctorant (3ème année) au CEFE, sous la direction de Sylvain Gandon. Je m’intéresse à l’adaptation dans un environnement temporellement variable et spatialement hétérogène.
